### ISSUE TITLE
build container automatically

### ISSUE THREAD

**Issue by yarikoptic** [con/opfvta-replication-2023#24]
my summary from matrix chat in the light of finding of a reason for #21: outdated image

Ideally it should be made/pushed automatically by a CI job in that repo upon modification of that recipe to avoid such issues
have a look e.g. at https://github.com/nipy/heudiconv/blob/master/.github/workflows/docker.yml workflow
just constrain to build only when that Containerfile modifies
also in that Containerfile adopt best practice from neurodocker -- put all apt lines to one line and then clean up after yourself
e.g. see here https://github.com/ReproNim/reproin/blob/master/Dockerfile#L16
add this "lesson" (containers get outdated -- need to be automated) to the paper as one of the lessons learned

**Comment by TheChymera** [comment]
@yarikoptic is this still active? if so could you detail it more?

**Comment by yarikoptic** [comment]
we have https://hub.docker.com/orgs/centerforopenneuroscience/ but so far I failed to "bind" a service user to this org to autotrigger updates.

**Comment by TheChymera** [comment]
@yarikoptic now that we're finally wrapping up, should we deal with this or close it?

**Comment by yarikoptic** [comment]
since not done, let's do `wontfix`
