### ISSUE TITLE
Numpy and Pandas in container

### ISSUE THREAD

**Issue by TheChymera** [con/opfvta-replication-2023#25]
For one of our latest figure generation scripts we will need the following software in the article-generating container:

* numpy
* pandas
* matplotlib
* seaborn

(given proper dependency management, seaborn would pull in all 3, but proper specification would be to explicitly depend on all 3, since we call them directly).

@asmacdo, how could we best do this? I've had issues re-generating the image to include `graphviz` already.

**Comment by asmacdo** [comment]
@TheChymera I wouldn't explicitly install them if they are pulled in as dependencies, can you explain the problem?

If you do want to explicitly include them, we can pip install from the Container file, but as a rule of thumb, mixing pip installs with system installation can cause problems.

**Comment by TheChymera** [comment]
> mixing pip installs with system installation can cause problems

Yep, I would agree.

> can you explain the problem?

* https://github.com/con/opfvta-replication-2023/blob/7073f33cdee4403741a29e7ea085723f0bba755c/paper/source/scripts/paperdiff_pages.py#L2
* https://github.com/con/opfvta-replication-2023/blob/7073f33cdee4403741a29e7ea085723f0bba755c/paper/source/scripts/paperdiff_pages.py#L3
* https://github.com/con/opfvta-replication-2023/blob/7073f33cdee4403741a29e7ea085723f0bba755c/paper/source/scripts/paperdiff_pages.py#L4
* https://github.com/con/opfvta-replication-2023/blob/7073f33cdee4403741a29e7ea085723f0bba755c/paper/source/scripts/paperdiff_pages.py#L5

We import them explicitly in the script, so we shouldn't rely on the fact that we know seaborn pulls in all of them. It might stop doing so at some point. I mean it won't, but this is the sort of implicit magick which should be avoided in good dependency specification.

**Comment by asmacdo** [comment]
Fixed
