### ISSUE TITLE
The imminent plan

### ISSUE THREAD

**Issue by yarikoptic** [con/opfvta-replication-2023#31]
- [x] do not re-partition to multiple containers but add to "Lessons learned" about necessity to modularize major steps into independent modules
- [x] fix for the failing execution.  Might relate to incorrect bindmount for scratch. (@TheChymera @asmacdo)
   - [x] debug while bind mounting
   - [x] do singularity run locally or on typhon -- make sure that it works
   - [ ] run on discovery directly, not via reproman
   - [ ] run with `reproman` through SLURM
- [ ] "Background section" needs to get more details on relevant to the original study/this reproduction aspects: which apps used and why not the other (fmriprep), possibly reduce generic descriptions about reproducibility aspects when not directly relating.  
- [ ] Reformat "Lessons learned" into major "paragraph messages", possibly splitting into "challenges" and "outlook"
- [ ] make clear(er) top level invocation rules: `all` to invoke all steps: `analysis-oci`, `article-data`, `article`. For that -- commit (into git directly) all article related figs/files so that `make article` would not rebuild those files.
   - [ ] `make article-data` should regenerate the diffs (@TheChymera)
- [ ] check and verbalize in the paper re-execution of re-execution via `git clone + cd + make all + git diff`.

**Comment by asmacdo** [comment]
this plan is no longer imminent, the comments are now obsolete
