### ISSUE TITLE
Missing graphics in meta-article

### ISSUE THREAD

**Issue by asmacdo** [con/opfvta-replication-2023#41]
Following README instructions I re-generated the meta article on typhon.

I'm not sure if some of the graphics need to be pulled down via git-annex or if we just have a rendering error

![image](https://github.com/con/opfvta-replication-2023/assets/1028657/74209e45-d9f3-450b-9d28-a300d927c646)

Full article attached
[article-1.pdf](https://github.com/con/opfvta-replication-2023/files/12750289/article-1.pdf)

**Comment by TheChymera** [comment]
This means that the diffs have not been generated. Are you sure you downloaded the article pdf data? Please post the output of:

```console
 ls outputs/*/*pdf -lah
 ```

**Comment by asmacdo** [comment]
Looks like `make container-article` always does a clean, so that isn't the problem. (Btw, `make article-clean` only works with latex installed, so we might need to check that the container is doing this successfully?)

`$ ls outputs/*/*pdf -lah`

```
lrwxrwxrwx 1 asmacdo asmacdo 136 Sep 21 16:22 outputs/original/article.pdf -> ../../.git/annex/objects/f9/Pv/MD5E-s21852357--cda3904485734ab5c089894db1659fa0.pdf/MD5E-s21852357--cda3904485734ab5c089894db1659fa0.pdf
lrwxrwxrwx 1 asmacdo asmacdo 136 Sep 21 16:22 outputs/podman_20230906053037/article.pdf -> ../../.git/annex/objects/qW/zV/MD5E-s21529647--17365d13a65885d2fce3d65d1c96c9f7.pdf/MD5E-s21529647--17365d13a65885d2fce3d65d1c96c9f7.pdf
lrwxrwxrwx 1 asmacdo asmacdo 136 Sep 21 16:22 outputs/podman_20230908162849/article.pdf -> ../../.git/annex/objects/80/v6/MD5E-s21545132--cc38b0844b952a39cd8d4cbf96605105.pdf/MD5E-s21545132--cc38b0844b952a39cd8d4cbf96605105.pdf
lrwxrwxrwx 1 asmacdo asmacdo 136 Sep 21 16:22 outputs/podman_20230920004219/article.pdf -> ../../.git/annex/objects/PJ/0J/MD5E-s21532977--fd1bd9e0b630500be88a52f3880f7a96.pdf/MD5E-s21532977--fd1bd9e0b630500be88a52f3880f7a96.pdf
lrwxrwxrwx 1 asmacdo asmacdo 136 Sep 21 16:22 outputs/podman_20230920004416/article.pdf -> ../../.git/annex/objects/gx/Pj/MD5E-s21514941--990e16b8bb32fb21c65c71a73646301d.pdf/MD5E-s21514941--990e16b8bb32fb21c65c71a73646301d.pdf
-rw-r--r-- 1 asmacdo asmacdo 21M Sep 23 02:44 outputs/podman_20230922123546/article.pdf
lrwxrwxrwx 1 asmacdo asmacdo 136 Sep 21 16:22 outputs/singularity_20230904214036/article.pdf -> ../../.git/annex/objects/k1/6x/MD5E-s21487275--5ab7da033717219cf2b87dde21317777.pdf/MD5E-s21487275--5ab7da033717219cf2b87dde21317777.pdf
lrwxrwxrwx 1 asmacdo asmacdo 136 Sep 21 16:22 outputs/singularity_20230905040926/article.pdf -> ../../.git/annex/objects/16/fV/MD5E-s21487288--ad7b66af092f14b60d45b31ba5e09135.pdf/MD5E-s21487288--ad7b66af092f14b60d45b31ba5e09135.pdf
lrwxrwxrwx 1 asmacdo asmacdo 136 Sep 21 16:22 outputs/singularity_20230905204435/article.pdf -> ../../.git/annex/objects/wz/g9/MD5E-s21487302--9f76897f47716f6adda8c778917b920d.pdf/MD5E-s21487302--9f76897f47716f6adda8c778917b920d.pdf
lrwxrwxrwx 1 asmacdo asmacdo 136 Sep 21 16:22 outputs/singularity_20230906012936/article.pdf -> ../../.git/annex/objects/8v/q0/MD5E-s21551881--c92d2d5f2941e0a5a4eb25fca28a92ec.pdf/MD5E-s21551881--c92d2d5f2941e0a5a4eb25fca28a92ec.pdf
lrwxrwxrwx 1 asmacdo asmacdo 136 Sep 21 16:22 outputs/singularity_20230908122618/article.pdf -> ../../.git/annex/objects/K6/vv/MD5E-s21370913--dd4358584c78e366bc7940ed7c0965a8.pdf/MD5E-s21370913--dd4358584c78e366bc7940ed7c0965a8.pdf
```

I'm not in a clean git state though. After executing the analysis, commit steps aren't included in the readme. Is it safe to just commit these partial results so I can rebase onto your recent changes?

**TODO: We should include commit points into the readme.**

or

**TODO (asmacdo preference): We should change the make targets to `datalad run` 

It does look like this is just an environment problem, since CI is building the pdf with images successfully.

**Comment by yarikoptic** [comment]
Use `ls -lL` to see if you actually feed the data

**Comment by asmacdo** [comment]
`$ ls -lLah outputs/*/*.pdf`

```
-r--r--r-- 1 asmacdo asmacdo 21M Sep 25 10:36 outputs/original/article.pdf
-r--r--r-- 1 asmacdo asmacdo 21M Sep 25 10:33 outputs/podman_20230906053037/article.pdf
-r--r--r-- 1 asmacdo asmacdo 21M Sep 25 10:31 outputs/podman_20230908162849/article.pdf
-r--r--r-- 1 asmacdo asmacdo 21M Sep 25 10:35 outputs/podman_20230920004219/article.pdf
-r--r--r-- 1 asmacdo asmacdo 21M Sep 25 10:33 outputs/podman_20230920004416/article.pdf
-rw-r--r-- 1 asmacdo asmacdo 21M Sep 23 02:44 outputs/podman_20230922123546/article.pdf
-r--r--r-- 1 asmacdo asmacdo 21M Sep 25 10:32 outputs/singularity_20230904214036/article.pdf
-r--r--r-- 1 asmacdo asmacdo 21M Sep 25 10:37 outputs/singularity_20230905040926/article.pdf
-r--r--r-- 1 asmacdo asmacdo 21M Sep 25 10:32 outputs/singularity_20230905204435/article.pdf
-r--r--r-- 1 asmacdo asmacdo 21M Sep 25 10:34 outputs/singularity_20230906012936/article.pdf
-r--r--r-- 1 asmacdo asmacdo 21M Sep 25 10:35 outputs/singularity_20230908122618/article.pdf
asmacdo@typhon:~/tmp/opfvta-2023-9-21/opfvta-replication-2023$ 
```

**Comment by TheChymera** [comment]
After coworking session debugging it appears:

* The data is there
* Figures get generated with the correct aspect ration (thank to it being set explicitly in ghostscipr)
* However, figures are blank
* Though, the actual PDF diffs from which the figures are sliced by ghostscipt, are *not* blank

I conclude that this is probably some sort of ghostscirpt issue. The artifact on github CI is also correct (i.e. it shows figure contents), so probably we're trying to find something which is present on both github CI and on my machine, but not on @asmacdo 's account on typhon. This is very strange but we need to figure it out. @yarikoptic can you try it locally as well?

**Comment by TheChymera** [comment]
It could be that ghostscript has trouble operating without a display.

**Comment by TheChymera** [comment]
I think I have it, so we dynamically diff the latest 4 reexecutions, but for the figures an older one was hardcoded, which is why, in view of @asmacdo 's new reexecutions, the older pdf-diff which we were attempting to slice with ghostscript was no longer generated.
