### ISSUE TITLE
For consistency, `mv article meta-article`

### ISSUE THREAD

**Issue by asmacdo** [con/opfvta-replication-2023#43]
I think this path is hardcoded some places

In the README, we the use of the word "article" and "meta-article" to avoid confusion

**Comment by TheChymera** [comment]
@asmacdo how about we change the name of the original article to something like “reference article”, or “subject article”, “target article”.

**Comment by TheChymera** [comment]
Probably not reference article since I use that word a lot to qualify our aspirational goal of this work serving as a reexecution reference.

**Comment by asmacdo** [comment]
Theres a lot to move, and a lot of things this could break. It was a pretty pedantic point to begin with, now that I'm in these weeds I vote to close.
