### ISSUE TITLE
reproman run execution

### ISSUE THREAD

**Issue by yarikoptic** [con/opfvta-replication-2023#5]
- discovery is peculiar. While working with datalad it needs to be ensured that git-annex can work without jumping into adjusted branch mode. See https://dbic-handbook.readthedocs.io/en/latest/mri/dataaccess.html#specificsworkarounds on how to configure git-annex to use custom freeze/thaw scripts

- [x] Set up VPN for access
- [x] ~Reproman create resource Discovery~ (local instead)
- [x]  Use DBIC installed git-annex (link above)
- [X] ~Setup data orchestration~ (do it by hand instead)
- [X] Install datalad
- [X] Install reproman
- [x] Clone repo and `datalad get` each submodule
- [ ] create reproman run command in makefile
- [ PENDING] get more space on discovery

**Comment by asmacdo** [comment]
there were some long running issues, and it wasn't really necessary for the main point of the paper.
