### ISSUE TITLE
We should change the repo name

### ISSUE THREAD

**Issue by TheChymera** [con/opfvta-replication-2023#9]
It's too verbose, doesn't inspire confidence, and also wrong, since we're hardly producing a true replica of anything.

I suggest:

1. `opfvta-reexecution`
2. `yoda-opfvta`

I would prefer the latter as it would mesh well with discussing YODA at more length in the article. The former, however, has the advantage of being more self-explanatory. Actually I'm now not so sure I prefer one or the other :D 

@yarikoptic 
@asmacdo 

pls vote.

**Comment by asmacdo** [comment]
This highlights something that I think is a little bit more of an awkward problem, which is a fuzzy line between opfvta and this repo. I vote we don't change the repo name right now, and if we decide to clean up the original repo, a better name will suggest itself.

**Comment by TheChymera** [comment]
As of https://github.com/con/opfvta-replication-2023/commit/afaeaeddc9240af815086853d3d0f9016fb8f421 , this still fails:

```console
Latexmk: 'pdflatex': source 'data/topology' doesn't exist.
   I'll try making it with allowed extensions
------------
Running 'make "data/topology.jpg"'
------------
make: *** No rule to make target 'data/topology.jpg'.  Stop.
------------
Running 'make "data/topology.pdf"'
------------
pushd data; dot -Tpdf topology.dot -o topology.pdf 2> topology.log
/data/data /data
Makefile:41: recipe for target 'data/topology.pdf' failed
make: *** [data/topology.pdf] Error 127
------------
Running 'make "data/topology.png"'
------------
make: *** No rule to make target 'data/topology.png'.  Stop.
------------
Running 'make "data/topology.tex"'
------------
make: *** No rule to make target 'data/topology.tex'.  Stop.
Latexmk: Summary of warnings:
  Latex failed to resolve 15 citation(s)
Latexmk: Errors, in force_mode: so I tried finishing targets
Collected error summary (may duplicate other messages):
  biber article: Biber errors: See file 'article.blg'
  pdflatex: Command for 'pdflatex' gave return code 256
make: *** [Makefile:44: container-article] Error 12
[deco]~/docsrc/opfvta-replication-2023/paper/source ❱ cat data/topology.log
/bin/bash: dot: command not found
```

It appears to be the correct package name → https://manpages.debian.org/stretch/graphviz/dot.1.en.html

**Comment by TheChymera** [comment]
Not sure there's much fuzziness here. We are doing a study for which the input is this other study. We could have a completely different name (at the risk of putting ourselves in a position where we need to make a strong case for broad generalizability — could be done, I guess), or we could have aname which uses opfvta+<our core concept>. I think “replication-2023” sells our work way too short.

**Comment by yarikoptic** [comment]
I agree that `replication` is indeed off, and `reexecution` would be closer. On the other hand, I do not care enough about the name I guess - even current one is ok with.  It should probably include `opfvta` in it.  What matters more is to be done with it.  With renaming now would come hassle which would contribute to not "be done" with it even if for just little while.

**Comment by asmacdo** [comment]
The conclusion was yes, replication is not the best word choice, but since changing it would be so irritating we are leaving as is. CLOSED-WONTFIX

**Comment by TheChymera** [comment]
I renamed this because we need a proper repo title for SfN. No confusion on the poster.
